sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bfrAXQ+YhGuS0I+bMLFQBqPwZYsU6VI2L3kGPdaTYFLfGVgMqwR2a9WncIomKOomsKJXhMySoE2SNPmnVX8Gl91yVv2VVHmBdp5vBRiaTplu6OIO3nFunxeVj7yfx54nPXtaXO10JDsTtR5bWy/n6xgsnhQ6sKICZLlELH1SAlK0EhY8EB8CVhlIUYT7Rbwhr3Y6veQEWKKSZOY8EY9fRCyJa8+j5exPQ8pgEABvApHbQvXktx3j6PE73gVIEDJtvMC0gbNVFgWbbC0yw/LCZWyCjDi9eU/xZj0wgPSQ8ilNajls6K56Mx/GYkiesImL6JxIfM7yiZgfs6hitAk2hk4nbBRVxHKmERldHgmZ1UzN9xWBWi4TdJlwCUnSH5hVPlbRflzzJmCFam0ODjmwmlaoWizGhH/mirXanVhniMGdpU28iKkQbvJj2PWYCeJMiwoAi+ihcLS3mrv+JB8ifBgb4ZxmyceNn6qLDCNp0qzAxH3iaDeGrOHSBNyFl5OGAhEByWgJaurwmkkFfyzy6nXGdrIJjyf/BaNRswWMe5xksFI+bKWCICv5rrtJkacdFMn808v5c0jW6hbcRn/WniZi8a0hgu1WlJPnIuMPZicQjCcglHXliDW14hUHJamP2nr5GETtQrwrnq5IVMjsNYFkQIrclQ9q6X7p4G2QgeM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Eve-of-the-Revolution--A-Chronicle-of-the-Breach-with-England_3093
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy